### ISSUE TITLE
License

### ISSUE THREAD

**Issue by schloerke** [meztez/plumberDeploy#2]
Moving discussion from https://github.com/meztez/plumberDeploy/pull/1#issuecomment-674114847

cc @muschellij2 

---------------------

Plumber is MIT: https://github.com/rstudio/plumber/blob/38d5fd706fe62e85222993687b1d695b0c044b58/DESCRIPTION#L14

I don't know if `plumber` should be held as an Author with role of `cph`.  Then, I think we could still keep it as MIT.

Right? (License's are not my strong suit)

**Comment by cpsievert** [comment]
Should probably also add Jeff as an author?

**Comment by meztez** [comment]
yes, of course
