### ISSUE TITLE
Error: 404  Not Found / Unable to fetch some arch

### ISSUE THREAD

**Issue by rwblackburn** [meztez/plumberDeploy#31]
Starting w/basic install. 

Getting the following error:
```
> mydrop <- plumberDeploy::do_provision()
THIS ACTION COSTS YOU MONEY!
Provisioning a new server for which you will get a bill from DigitalOcean.
Using default ssh keys: Justin's SSH, Kelly's SSH, Rob's R Studio, Rob's SSH
NB: This costs $0.00744 / hour until you droplet_delete() it
Waiting for create .....................
New server key: 3f:bd:ad:27:f5:db:ec:9a:66:00:f5:e6:b4:db:ba:1b:4f:60:aa:3a
         2 /private/var/folders/9s/ksk9hjhs4d1f16j6xxrdny9m0000gn/T/RtmpiOnzCE/BwOaUyRxPl

Setting up swapspace version 1, size = 4 GiB (4294963200 bytes)
no label, UUID=942d7a84-5a8b-4929-a74f-1fa86e3e4205
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20210119~20.04.1).
ca-certificates set to manually installed.
dirmngr is already the newest version (2.2.19-3ubuntu2.1).
dirmngr set to manually installed.
gnupg is already the newest version (2.2.19-3ubuntu2.1).
gnupg set to manually installed.
software-properties-common is already the newest version (0.98.9.5).
software-properties-common set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 1704 B of archives.
After this operation, 161 kB of additional disk space will be used.
Err:1 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.5
  404  Not Found [IP: 104.21.29.13 80]
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Failed to fetch http://mirrors.digitalocean.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.0.5_all.deb  404  Not Found [IP: 104.21.29.13 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: ssh failed
sudo apt-get install -y --force-yes dirmngr gnupg apt-transport-https ca-certificates software-properties-common
```

Checked `ssh::ssh_key_info()` and it shows the expect SSH private key.
Checked `lapply(analogsea::keys(), '[[', "public_key")` and it contains the expected SSH public key.

Any suggested next steps would be appreciated.

**Comment by rwblackburn** [comment]
The droplet is created, but calling it w/cURL returns:
```
curl: (7) Failed to connect to 123.123.123.123 port 8000: Connection refused
```

**Comment by rwblackburn** [comment]
Doing this:
```
analogsea::droplet_ssh(mydroplet, "whoami", verbose = TRUE)
```
Returns (after a very long time):
```
whoami
Error: libssh failure at 'ssh_channel_open_session': Socket error: Operation timed out
```
Not sure if that has anything to do with this. Other `analogsea` functions work fine. For example `analogsea::droplets()` or `analogsea::droplet(id)` both work fine.

**Comment by meztez** [comment]
it seems the droplet was not able to fetch a ubuntu package from DO mirrors. I'll investigate.

**Comment by meztez** [comment]
I've added an extra apt update step to R install step. Seems DO ubuntu image can get out of sync with DO mirrors. You can try it using the latest from github using
```r
# install.packages("remotes")
remotes::install_github("meztez/plumberDeploy")
```

Let me know if this helps @rwblackburn

**Comment by rwblackburn** [comment]
@meztez 
Ran `install.packages("remotes")` and `remotes::install_github("meztez/plumberDeploy")` successfully. 

Unfortunately, `plumberDeploy::do_provision()` still throws the same error.

**Comment by meztez** [comment]
@rwblackburn did you restart R for the package change to take effect?. It worked when I tried it yesterday.

**Comment by rwblackburn** [comment]
Yep, I restarted. 

I just did it again to be sure (rebooted the whole system even). Same errror. The only difference is the IP address in the 404 messgage:
```
404  Not Found [IP: 172.67.148.71 80]
```

**Comment by meztez** [comment]
Damn, I'm sorry to hear that. I've updated the dev version only, as it works fine when I test it. Make sure you are using plumberDeploy 0.2.1.10000.

IP is just a mirror

**Comment by rwblackburn** [comment]
Looks like I am on 0.2.1
```
> packageVersion("plumberDeploy")
[1] ‘0.2.1’
```

**Comment by rwblackburn** [comment]
I just re-ran `remotes::install_github("meztez/plumberDeploy")`
And now I seem to be on `0.2.1.10000`:
```
> packageVersion("plumberDeploy")
[1] ‘0.2.1.10000’
```
I promise I ran that before (twice). Maybe there was a lag in GitHub publishing that version?

**Comment by rwblackburn** [comment]
@meztez  - This is not working. Thank you for the assistance.

**Comment by meztez** [comment]
@rwblackburn now working or not working?

**Comment by rwblackburn** [comment]
“now working”, my apologies
