### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by schloerke** [meztez/plumberDeploy#5]
Does this package have a timeline to release to CRAN?

Just so I know how to do the wording / function calling on `plumber`.

Thank you! 🙌 

cc @cpsievert

**Comment by meztez** [comment]
We are in the middle of team switching, I'll probably have some more time comes september. I would say first submit october 1st.

**Comment by muschellij2** [comment]
Can we bump this thread?  Without this on CRAN, one of my papers won't be reviewed in JSS.

**Comment by meztez** [comment]
You can submit the package if you have time, I do not at the moment : https://www.r-bloggers.com/2020/10/submitting-r-package-to-cran/

**Comment by blairj09** [comment]
Just checking back in on CRAN status / timeline :grin:

**Comment by meztez** [comment]
I'll circle back to this mid april.

**Comment by muschellij2** [comment]
I have run through the checks and it passes.  
I ran through the example (interactively and locally):
```r
  auth = try(analogsea:::do_oauth())
  if (!inherits(auth, "try-error") &&
      inherits(auth, "request")) {
    analogsea::droplets()
    droplet = do_provision(region = "sfo3", example = FALSE)
    analogsea::droplets()
    analogsea::install_r_package(droplet, c("readr", "remotes"))
    do_deploy_api(droplet, "hello",
                  system.file("plumber", "10-welcome", package = "plumber"),
                  port=8000, forward=TRUE)
    browseURL(paste0(plumberDeploy:::droplet_ip(droplet), "/hello"))
    analogsea::droplet_delete(droplet)
  }
```
and it works.  Note the `region = "sfo3"` as my issue https://github.com/sckott/analogsea/issues/205 indicates `sfo2` (the default) does not seem to be working out of the box.

**Comment by muschellij2** [comment]
Looks good to me: https://win-builder.r-project.org/MnbgHCZWICmg/

**Comment by meztez** [comment]
CRAN response

Thanks,

Please add \value to .Rd files regarding exported methods and explain 
the functions results in the documentation. Please write about the 
structure of the output (class) and also what the output means. (If a 
function does not return a value, please document that too, e.g. 
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      do_configure_https.Rd: \value
      do_deploy_api.Rd: \value
      do_forward.Rd: \value
      do_provision.Rd: \value
      do_remove_api.Rd: \value
      do_remove_forward.Rd: \value

You have examples for unexported functions.
Please either omit these examples or export these functions.
Used ::: in documentation:
      man/do_provision.Rd:
         auth = try(analogsea:::do_oauth())
      man/do_provision.Rd:
         if (!inherits(auth, "try-error") && inherits(auth, "request")) {
  analogsea::droplets()
  droplet = do_provision(region = "sfo3", example = FALSE)
  analogsea::droplets()
  analogsea::install_r_package(droplet, c("readr", "remotes"))
  do_deploy_api(droplet, "hello", system.file("plumber", "10-welcome", 
package = "plumber"), port = 8000, forward = TRUE)
  browseURL(paste0(plumberDeploy:::droplet_ip(droplet), "/hello"))
  analogsea::droplet_delete(droplet)

Please always add all authors, contributors and copyright holders in the 
Authors@R field with the appropriate roles.
e.g.: Trestle Technology, LLC
Please explain in the submission comments what you did about this issue.


Please fix and resubmit.

Best,
Gregor Seyer

**Comment by muschellij2** [comment]
https://github.com/meztez/plumberDeploy/pull/25 fixes all of them except 
```
Please always add all authors, contributors and copyright holders in the
Authors@R field with the appropriate roles.
e.g.: Trestle Technology, LLC
Please explain in the submission comments what you did about this issue.
```
Can you address (or tell me how you'd like this addressed) @meztez @trestletech for the DESCRIPTION file?

**Comment by meztez** [comment]
I've update the description file, with the appropriate roles and cph holders role

**Comment by muschellij2** [comment]
Resubmitted

**Comment by meztez** [comment]
>Thanks,
>on its way to CRAN.
>
>Best,
>Gregor Seyer

@muschellij2 Thanks a lot
